name: .NET 8 CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    # Set up .NET SDK 8.0
    - name: Set up .NET SDK 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Restore dependencies for the solution
    - name: Restore dependencies
      run: dotnet restore ./BookLibrary.sln

    # Build API Docker Image
    - name: Build BookLibrary API Docker Image
      working-directory: ./BookLibrary.Api
      run: |
        docker build -t booklibrary-api .

    # Build Test Docker Image
    - name: Build BookLibrary Tests Docker Image
      working-directory: ./BookLibrary.Tests
      run: |
        docker build -t booklibrary-tests .

    # Run Tests in Test Docker Container
    - name: Run BookLibrary Tests in Docker
      run: |
        docker run --rm booklibrary-tests

    # Optionally, push Docker images to Docker Hub
    # Log in to Docker Hub (if using Docker Hub)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push BookLibrary API Docker Image to Docker Hub (Optional)
    - name: Push BookLibrary API Docker Image
      run: |
        docker push booklibrary-api

    # Push BookLibrary Tests Docker Image to Docker Hub (Optional)
    - name: Push BookLibrary Tests Docker Image
      run: |
        docker push booklibrary-tests
