name: Build, Test, and Deploy

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests to the main branch

jobs:
  # Job to build and deploy the API project
  build-and-deploy-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image for API
      - name: Build Docker image for API
        run: |
          docker build -f BookLibrary.Api/Dockerfile -t book-api-img .

      # Optionally, push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag book-api-img ${{ secrets.DOCKER_USERNAME }}/booklibrary-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/booklibrary-api:latest

      # Optionally deploy the Docker container (e.g., to AWS, Azure, or your server)
      # Add your deployment steps here if applicable

  # Job to build and run tests for the test project
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image for Tests
      - name: Build Docker image for Tests
        run: |
          docker build -f BookLibrary.Tests/Dockerfile -t book-test-img .

      # Run the tests
      - name: Run tests
        run: |
          docker run --rm book-test-img

    